### ISSUE TITLE
Add container queries to the ui components

### ISSUE THREAD

**Issue by NilsJacobsen** [stagehq/ui#1]
On the backend side of the project we have some use cases, where we want to shrink the portfolio between to sidebars. But because the window doesn't change I see a need for container queries here.

Since tailwind shipped their own first party plugin, we should integrate it.
https://github.com/tailwindlabs/tailwindcss-container-queries

The usage is to add @container class, and then applying styles based on the size of that container using the container variants like @md:, @lg:, and @xl::

```jsx
<div class="@container">
  <div class="@lg:underline">
    <!-- This text will be underlined when the container is larger than `32rem` -->
  </div>
</div>
```

**Comment by NilsJacobsen** [comment]
Added `@container` to the main container of the page. All queries that were nested in this component are `lg`, `md`, `sm`

I taped those queries on the most similar values of container queries. 
`lg` -> `@6xl`
`md` -> `@3xl`
`sm` -> `@2xl`

**Comment by felixhaeberle** [comment]
Seems to work quite well! Should we add an additional page to Storybook for showcasing this behavior and in particular to debug it? I suggest a Container with a fixed size where the page then gets rendered as with "Mobile" or "Tablet" width size.
@NilsJacobsen What do you think?

**Comment by felixhaeberle** [comment]
Nice!! Can we remove the duplicate component for the different viewports declarations with creating an separate object and assign it to the viewport instance stories?

**Comment by NilsJacobsen** [comment]
@felixhaeberle isolated the arguments Object, to remove the duplication
