### ISSUE TITLE
Create a Block Component

### ISSUE THREAD

**Issue by NilsJacobsen** [stagehq/ui#3]
Create a block component to realize a card look for each block. 
<img width="815" alt="image" src="https://user-images.githubusercontent.com/58360188/210521815-aa058f27-5713-4105-99c3-0757b5b698e9.png">

Suggestion: 
Header should be integrated in the block. 
The title should be editable for users. 
Header image comes from the api connector. 
Underlaying components are accessible through: Block.List, Block.Card, Block.Pills, Block.Separator ...

Questions: How can we store the title of the block from our UI component. We could add a title field in the extension table of the db. Then the block component only needs to know user and block context to call the mutation. Maybe we can pass in a function that handles title changes and gets user and block context from a recoil store.

Steps: 
- [x] Add block component
- [x] Integrate new header in it
- [x] Remove old header
- [x] Access underlying components via Block.List notation
- [x] Make header title editable
- [x] Add a change handler function
- [x] Create stories for common blocks
- [x] Create stories for the three block sizes -> use container queries
- [x] Work on hover states
- [x] Test
- [ ] Publish

**Comment by felixhaeberle** [comment]
Closing this because #4 merged
